

repos:
-   repo: local
    hooks:
    -   id: test
        name: run tests
        entry: pytest
        language: python
        language_version: python3
        
        pass_filenames: false
        
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black












