

repos:
- repo: local
  hooks:
  - id: pylint
    name: pylint Shop App
    entry: pylint ./shop_app
    language: python
    files: \.py$
    args:
        [
          "--errors-only",
          --output-format=colorized,
          --max-line-length=120
        ]
